#!/bin/bash
set -e

# -------------------------------------
#  MMZC GBA Script Restoration
#  Optimized Build Script (Linux)
# -------------------------------------

# --- Output and paths ---
OUTPUT_NAME="MMZC Spanish Script.dll"
BUILD_DIR="build"
FINAL_PATH="$BUILD_DIR/$OUTPUT_NAME"

# --- Compiler optimization flags ---
CXXFLAGS="-std=c++17 -Oz -flto -ffunction-sections -fdata-sections -fomit-frame-pointer -fvisibility=hidden -fno-exceptions -fno-rtti -fno-unwind-tables -fno-asynchronous-unwind-tables -march=x86-64 -mtune=generic -Wall"
LDFLAGS="-shared -flto -fuse-ld=lld -Wl,--gc-sections -Wl,--icf=all -Wl,--build-id=none"

# --- Toolchain binaries ---
CXX="clang++"
STRIP="llvm-strip"

# --- Color helpers ---
green="\033[1;32m"
cyan="\033[1;36m"
yellow="\033[1;33m"
reset="\033[0m"

# --- Help message ---
if [[ "$1" == "--help" || "$1" == "-h" ]]; then
    echo -e "${cyan}MMZC Spanish Script - Build Script (Linux)${reset}"
    echo
    echo -e "Usage: ./build.sh [option]"
    echo
    echo -e "Options:"
    echo -e "  ${yellow}clean${reset}   Remove all build files and generated headers."
    echo -e "  ${yellow}[none]${reset}  Perform a full CMake build (default)."
    echo
    echo -e "Example:"
    echo -e "  ./build.sh clean"
    echo
    exit 0
fi

# --- Clean mode ---
if [[ "$1" == "clean" ]]; then
    echo -e "${cyan}[*] Cleaning project...${reset}"

    # Remove build folder and binaries
    rm -rf "$BUILD_DIR"
    rm -f *.dll *.dll.a *.obj *.o *.log

    # Remove files generated by prebuild.py
    find tpl -type d \( -name "mmz1_msg" -o -name "mmz2_msg" -o -name "mmz3_msg" -o -name "mmz4_msg" -o -name "log" \) -exec rm -rf {} +

    # Remove generated headers from the project root
    rm -f mmz1_msg.h mmz1_font.h \
          mmz2_msg.h mmz2_font.h \
          mmz3_msg.h mmz3_font.h \
          mmz4_msg.h mmz4_font.h

    echo -e "${green}[✔] Clean complete.${reset}"
    exit 0
fi

# --- Full CMake build mode ---
echo -e "${cyan}[*] Building with CMake (full mode, Release)...${reset}"
rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR" && cd "$BUILD_DIR"

cmake .. -DCMAKE_TOOLCHAIN_FILE=../toolchain-clang.cmake \
         -DCMAKE_BUILD_TYPE=Release \
         -DCMAKE_CXX_FLAGS_RELEASE="$CXXFLAGS" \
         -DCMAKE_SHARED_LINKER_FLAGS_RELEASE="$LDFLAGS"

make -j"$(nproc)"
cd ..

# --- Find generated DLL ---
DLL_PATH=$(find "$BUILD_DIR" -maxdepth 1 -type f -name "$OUTPUT_NAME" | head -n1)
if [[ -z "$DLL_PATH" ]]; then
    echo "[✖] DLL not found!"
    exit 1
fi

# --- Strip debug symbols ---
echo -e "${cyan}[*] Stripping debug symbols...${reset}"
$STRIP "$DLL_PATH"

# --- Show final result ---
SIZE=$(du -h "$DLL_PATH" | cut -f1)
echo -e "${green}[✔] Build complete: $DLL_PATH (${SIZE})${reset}"
